### ISSUE TITLE
Add statistic capabilities

### ISSUE THREAD

**Issue by neuholdm** [n0r1sk/smsgateway#42]
API to trigger stat transmission
think about useful stats

**Comment by m4r10k** [comment]
Start to implement an appropriate logstash forwarder based upon the http plugin https://www.elastic.co/blog/introducing-logstash-input-http-plugin 

@neuholdm extend database driver to read successful (4|5) sends and order by statustime

**Comment by neuholdm** [comment]
add a table to hold last time stamp sent too

**Comment by neuholdm** [comment]
read_sucsmsstats
write_statstimestamp
read_statstimestamp

added

**Comment by m4r10k** [comment]
Time scheduling through a separate thread is annoying, because it needs a watchdog and much more. I will implement this as a rest interface which could be triggered through cron.
