### ISSUE TITLE
Persistent queue

### ISSUE THREAD

**Issue by davistan** [n0r1sk/smsgateway#48]
Hi and nice project! Just wondering any queue mechanism in place if there is an overload traffic to outgoing sms and also to save to disk in case of system crash.

Thanks.

**Comment by m4r10k** [comment]
Yes, this is resolved through the local SQLite database. If the web interface received sendsms requests (threaded through webserver), the data is always stored into the database first. Afterwards a thread is triggered and this thread will process the SMS from database until there are no new SMS to send. If the server dies during this process the unsend SMS will be processed as usual after restart. Database entries will be deleted automatically after 90 days (configurable).

**Comment by davistan** [comment]
Thank you for such a descriptive reply.

**Comment by m4r10k** [comment]
No problem :)
